# Site
name: "_Gymon Blog"
title: "_Gymon Blog"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll


## Google Analytics es una herramienta gratuita de análisis web que te permite rastrear y analizar el tráfico de tu sitio web, incluyendo la cantidad de visitantes, la procedencia de los visitantes, las páginas más visitadas, etc.
## Para utilizar Google Analytics, debes crear una cuenta en el sitio web de Google Analytics y obtener un código de seguimiento (como el que se muestra en la línea de código). Luego, debes agregar este código a tu sitio web para que Google Analytics pueda rastrear el tráfico.
google_analytics: ''

## Disqus es una plataforma de comentarios que te permite agregar comentarios a tu sitio web de manera fácil y segura.
#Para utilizar Disqus, debes crear una cuenta en el sitio web de Disqus y obtener un código de configuración (como el que se muestra en la línea de código). Luego, debes agregar este código a tu sitio web para que Disqus pueda funcionar correctamente.
## Disqus ofrece planes gratuitos y de pago. El plan gratuito te permite agregar comentarios a tu sitio web, pero con algunas limitaciones. Los planes de pago ofrecen más características y funcionalidades avanzadas.
## Solo es gratuita por 30 dias, por lo que no es una buena opcion. seria mejor hacer los comentarios en sinatra
disqus: ''

## Mailchimp es una plataforma de marketing por correo electrónico y automatización de marketing que permite a los usuarios crear y enviar campañas de correo electrónico personalizadas a sus suscriptores.
## Se puede usar Mailchimpo Mailjet que son gratis
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: author1
    display_name: author1
    gravatar:
    email: author1@gmail.com
    web: https://www.example1.com
    twitter: https://twitter.com/author1
    description: "Author of gymonblog, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: author2
    display_name: author2
    avatar: 'assets/images/avatar.png'
    gravatar:
    email: author2@gmail.com
    web: https://www.example2.com
    twitter: https://twitter.com/author2
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
